### ISSUE TITLE
Intermittent failure on graphQLHandler.setup

### ISSUE THREAD

**Issue by pnacht** [ossf/scorecard-action#1000]
The error given is:

> internal error: ListCommits:error during graphqlHandler.setup: internal error: githubv4.Query: non-200 OK status code: 502 Bad Gateway body: "{\n   \"data\": null,\n   \"errors\":[\n      {\n         \"message\":\"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `04C0:42FC:18AD2A3:328AC33:6358827B` when reporting this issue.\"\n      }\n   ]\n}\n"

I've seen https://github.com/ossf/scorecard-action/issues/784, but this is running @v2.0.3.

Observed in [pytorch](https://github.com/pytorch/pytorch/actions/runs/3325246910) a week ago. They have since disabled the Action because of these intermittent failures https://github.com/pytorch/pytorch/pull/87740, so I cannot determine if the failures would still be ongoing.

The run linked to above is currently on [page 8 of runs](https://github.com/pytorch/pytorch/actions/workflows/scorecards.yml?page=8), but it's a very active repo, so may be further down the list by the time you read this!

However, just a day before, there were no such failures (see page 10 of runs). Was this an instability in the graphQL API or an underlying bug?

**Comment by spencerschrock** [comment]
We see a related error in about 10% of graphQL queries. Still need to dig deeper, but my best guess is some sort of instability on the graphql API or we're close to a processing timeout which makes the call fail intermittently.

I can take another look since this is causing issues for repos

**Comment by spencerschrock** [comment]
I'm assuming this was fixed via https://github.com/ossf/scorecard/pull/3680
