### ISSUE TITLE
Failing e2e tests - scorecard-latest-release on pnacht/scorecard-action_update_sarif_v2

### ISSUE THREAD

**Issue by pnacht** [ossf/scorecard-action#1007]
Matrix: null
Repo: https://github.com/pnacht/scorecard-action_update_sarif_v2/tree/main
Run: https://github.com/pnacht/scorecard-action_update_sarif_v2/actions/runs/3448935549
Workflow name: scorecard-latest-release
Workflow file: https://github.com/pnacht/scorecard-action_update_sarif_v2/tree/main/.github/workflows/scorecards-latest-release.yml
Trigger: schedule
Branch: main

**Comment by spencerschrock** [comment]
Failure seems due to API limit, only one run failed. Should be safe to ignore this failure.
