### ISSUE TITLE
doc: update doc on use of PAT for private repositories

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard-action#1020]
We need to verify whether PATs are still needed for private repositories, and update the doc if they are not.

**Comment by LeviPesin** [comment]
They are [still needed](https://github.com/community/community/discussions/40910).

**Comment by laurentsimon** [comment]
Sorry. Here we want to verify whether "normal PATs" are needed for private repositories.

**Comment by joshjohanning** [comment]
What is the PAT needed for? 

In a test private repo, I was able to get this to work without a PAT. But I did comment out all of the `permissions` lines, which obviously yields 'findings' from this scan action.

**Comment by laurentsimon** [comment]
I think the PAT is needed for the branch protection check. You can keep the permissions line and it should work still work, but except for the branch protection check.

**Comment by joshjohanning** [comment]
> I think the PAT is needed for the branch protection check.

ahh that makes sense
