### ISSUE TITLE
How to use the github action to scan other public repositories?

### ISSUE THREAD

**Issue by sfc-gh-smisra** [ossf/scorecard-action#1133]
I have a workflow file, which checks out the public repo and then is supposed to scan it. But, right now, it is only scanning the repo from where the the action is run. let me know, what parameter I should use in action step to achieve my goal
`name: Scorecards supply-chain security
on:
  push:

# Declare default permissions as read only.
permissions: read-all

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      #security-events: write
      # Used to receive a badge. (Upcoming feature)
      id-token: write
      actions: read
      contents: read

    steps:
      - name: "Checkout code"
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
        with:
          repository: 'shioyang/check-pr-labels-on-push-action'
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@3e15ea8318eee9b333819ec77a36aca8d39df13e # tag=v1.1.1
        with:
          results_file: results.sarif
          results_format: sarif
          # (Optional) "write" PAT token. Uncomment the `repo_token` line below if:
          # - you want to enable the Branch-Protection check on a *public* repository, or
          # - you are installing Scorecards on a *private* repository
          # To create the PAT, follow the steps in https://github.com/ossf/scorecard-action#authentication-with-pat.
          # repo_token: ${{ secrets.SCORECARD_TOKEN }}

          # Publish the results for public repositories to enable scorecard badges. For more details, see
          # https://github.com/ossf/scorecard-action#publishing-results.
          # For private repositories, `publish_results` will automatically be set to `false`, regardless
          # of the value entered here.
          publish_results: true

      # Upload the results as artifacts (optional). Commenting out will disable uploads of run results in SARIF
      # format to the repository Actions tab.
      - name: "Upload artifact"
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3.0.0
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      # Upload the results to GitHub's code scanning dashboard.
      #- name: "Upload to code-scanning"
       # uses: github/codeql-action/upload-sarif@5f532563584d71fdef14ee64d17bafb34f751ce5 # tag=v1.0.26
        #with:
         # sarif_file: results.sarif
`

**Comment by naveensrinivasan** [comment]
Is your goal to run scans on other repositories? 

You should be able to achieve that with the Scorecard CLI

**Comment by sfc-gh-smisra** [comment]
Yeah I know that, is it not possible to do it with GitHub Action?

**Comment by naveensrinivasan** [comment]
> Yeah I know that, is it not possible to do it with GitHub Action?

It isn't designed for that purpose.

**Comment by spencerschrock** [comment]
There's also https://github.com/UlisesGascon/openssf-scorecard-monitor that may meet your needs.

**Comment by naveensrinivasan** [comment]
> There's also https://github.com/UlisesGascon/openssf-scorecard-monitor that may meet your needs.

I am closing the issue. If you need additional answers, please reopen.
