### ISSUE TITLE
🐛 Unexpected input errors

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard-action#114]
The latest release of Scorecard is spitting out this error on every run:

![image](https://user-images.githubusercontent.com/4825078/155422522-a1ba2ac7-5c5b-4dc0-8fd5-f99a37bb31e2.png)

**Comment by laurentsimon** [comment]
can you link to the workflow you're using? The error says the workflow is calling the action with the wrong argument `share_results` instead of `publish_results`.
This can happen if you used an old workflow, since we change the name of the argument a while back.

Can you verify?

**Comment by azeemshaikh38** [comment]
Ah, I see. Sent https://github.com/ossf/scorecard/pull/1674
