### ISSUE TITLE
Scores not included in the results

### ISSUE THREAD

**Issue by rio-56** [ossf/scorecard-action#115]
Currently, the results uploaded as artifacts to the Action tab don't include "scores" (i.e. X/10). Would it be possible to include the scores in the results?

(This is not an issue but a suggestion. But because this project doesn't have Discussion enabled, I didn't know where else to bring this up. My apologies for cluttering Issues.)

**Comment by laurentsimon** [comment]
Hi

thanks for reaching out!

For certain checks, we do show the score, see https://github.com/ossf/scorecard/blob/main/pkg/sarif.go#L518-L520

We display the score for *some* checks such as Code-Review, Dependency-Update-Tool, Branch protection, but not all checks. 

It should not be too hard to add it for all. Which checks would you like to see the score reported as well? All of them?

**Comment by rio-56** [comment]
Hi, thank you for your quick response and pointing me to the code snippet! If I'm not mistaken, based on [this line](https://github.com/ossf/scorecard/blob/504f13441636dcc6273d45d9dc1e7ea1ef080ae2/pkg/sarif.go#L431), a score should be displayed in `results:message:text` (for some checks). But I still don't think I see it at all even for the checks you mentioned.. Can you take a look at the following sample output?

- Branch-Protection:  
  ![image](https://user-images.githubusercontent.com/49325323/155634301-7102769e-1987-47cd-b7ef-9edf11b8456a.png)
  
- Dependency-Update-Tool:
  ![image](https://user-images.githubusercontent.com/49325323/155634265-b1da90a7-8194-4f95-a1e7-1ffc72cf1640.png)

- Code-Review:
  ![image](https://user-images.githubusercontent.com/49325323/155634328-0cda45c6-38a9-4d34-a6a7-3722f4baa8e6.png)

(This is an output from a sample Action run from an empty repository with just a workflow file that looks like [this](https://github.com/ossf/scorecard-action#workflow-example).)

> It should not be too hard to add it for all. Which checks would you like to see the score reported as well? All of them?

I actually would like to have scores for **all the checks** in artifacts, including 10/10 and -1(or ?)/10. I think the current output contains the results only for the checks for which 0 <= score < 10 though... would it be possible to include the scores for all the checks?

Thank you!

**Comment by laurentsimon** [comment]
ouch, sorry. The current GitHub action does not use the latest scorecard changes yet, that's why you don't see the results.
I think it's a fair ask to have all scores reported in the results. Can you create an issue on the main scorecard repo, and link to this issue? (the change needs to be made in the scorecard's code)

Thanks!
