### ISSUE TITLE
scorecard-action:v2.3.1 not found

### ISSUE THREAD

**Issue by konstruktoid** [ossf/scorecard-action#1285]
```
Error response from daemon: manifest for gcr.io/openssf/scorecard-action:v2.3.1 not found: manifest unknown: Failed to fetch "v2.3.1" from request "/v2/openssf/scorecard-action/manifests/v2.3.1".
```

https://github.com/konstruktoid/ansible-role-template/actions/runs/6618070089/job/17975722869#step:2:1

https://github.com/konstruktoid/ansible-role-template/pull/79#issue-1957878066

**Comment by konstruktoid** [comment]
Status: Downloaded newer image for gcr.io/openssf/scorecard-action:v2.3.1

Everything in sync.

**Comment by spencerschrock** [comment]
Yes, sadly there's a 4-5 minute window after tagging and before cloudbuild finishes the image. Renovate bot was speedy!
