### ISSUE TITLE
Change Scorecard Installation Template to use actions/checkout on version 4

### ISSUE THREAD

**Issue by diogoteles08** [ossf/scorecard-action#1287]
When I'm installing Scorecard directly through GitHub, the template for Scorecard workflow is using version 3.1.0, which should be updated since they have already released a new major version.

I tried to investigate where this change should be made but I couldn't figure it out. If you tell me how to do it I can contribute with a PR.

**Comment by diogoteles08** [comment]
The template could also be updated to have updated instructions on whether use a PAT token if you use Repo rules or Branch Protection rules

**Comment by spencerschrock** [comment]
> I tried to investigate where this change should be made but I couldn't figure it out. If you tell me how to do it I can contribute with a PR.

The starter workflow is here
https://github.com/actions/starter-workflows/blob/b1df8a546ed4d0f27d46aaf2f8ac1118bc522638/code-scanning/scorecard.yml

We should only make one update if possible, so before sending the PR, make sure we know what all we want to do.

**Comment by spencerschrock** [comment]
Done via https://github.com/actions/starter-workflows/pull/2348
