### ISSUE TITLE
Docs: Authentication

### ISSUE THREAD

**Issue by MichaelHinrichs** [ossf/scorecard-action#1301]
I got to this repo page from https://securityscorecards.dev/, "Using the GitHub Action" Step 2.  The link says `https://github.com/ossf/scorecard-action#authentication`, but there is no authentication section. there's even another broken link to this non-existent section in the very same document.
https://github.com/ossf/scorecard-action#troubleshooting

Without instructions on how to Authenticate my repository access, I don't know what to do.

**Comment by MichaelHinrichs** [comment]
It's public.

**Comment by spencerschrock** [comment]
> It's public.

Then the linked section above should be applicable. Authentication should be optional for public repos, happy to help with any issues
