### ISSUE TITLE
Error signing scorecard results

### ISSUE THREAD

**Issue by chungyc** [ossf/scorecard-action#1313]
For a couple of days, the OSSF Scorecard action has been failing in the "Run analysis" stage.
From https://github.com/haskell-actions/hlint-scan/actions/runs/7272836384/job/19815778861:

```
2023/12/20 08:35:03 error signing scorecard results: [GET /api/v1/log/entries/{entryUUID}][404] getLogEntryByUuidNotFound 
2023/12/20 08:35:03 retrying in 10s...
2023/12/20 08:35:13 error signing scorecard json results: error signing payload: [GET /api/v1/log/entries/{entryUUID}][404] getLogEntryByUuidNotFound 
```

The `"/api/v1/log/entries/{entryUUID}"` string suspiciously looks like a template parameter not being substituted.

This only started a few days ago, which is strange since the last release of the action was back in October.  The last time the action ran successfully was on 2023-12-18, as a published result shows: https://api.securityscorecards.dev/projects/github.com/haskell-actions/hlint-scan

**Comment by spencerschrock** [comment]
> For a couple of days, the OSSF Scorecard action has been failing in the "Run analysis" stage

I only see 2 failures from ~10 hours ago. https://github.com/haskell-actions/hlint-scan/actions/workflows/scorecard.yaml.
 Has this been happening elsewhere?
 
 > This only started a few days ago, which is strange since the last release of the action was back in October.
 
 We did have a [change on the API side of things](https://github.com/ossf/scorecard-webapp/releases/tag/v1.0.8), but this error is before that, on the scorecard-action side of things when signing with sigstore.
 
 I just manually dispatched a run in a test repo I was using earlier this week and it succeeded. [link](https://github.com/spencerschrock/scorecard-action-codeql-test/actions/runs/7279695636/job/19836542082)
 
 Perhaps it was an ephemeral sigstore issue?

**Comment by chungyc** [comment]
Yes, it was an ephemeral issue. 🤔

When it first started a few days ago, I thought it might be a transient issue and tried again every day, but as soon as I filed an issue because it no longer felt like a transient issue, it works. 😑
