### ISSUE TITLE
Feature: Feature-parity of Golang action 

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard-action#132]
@laurentsimon @azeemshaikh38 @naveensrinivasan -- Would you mind updating the issue description into the following sections:

- feature parity w/ `entrypoint.sh`
- new functionality

We should descope the Golang-based rollout to expressly the things that are required for feature parity with the current entrypoint and then take new functionality as follow-up actions.

_Originally posted by @justaugustus in https://github.com/ossf/scorecard-action/issues/79#issuecomment-1062490828_

**Comment by laurentsimon** [comment]
I (mistakenly?) created https://github.com/ossf/scorecard-action/issues/156.

**Comment by azeemshaikh38** [comment]
Closing this in favor of #156
