### ISSUE TITLE
Feature: Scorecard badges

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard-action#133]
This issue tracks the work being done as part of enabling Scorecard badges through Scorecard Action.

@rohankh532 fyi.

**Comment by azeemshaikh38** [comment]
@laurentsimon @naveensrinivasan @justaugustus - work on Golang action is now feature complete. So I'm proposing that we:

1) Lockdown any changes/features to Bash code.
2) Make a pre-release of the Golang Action code and ask some maintainers to become early adopters and provide feedback. Can take help from OSSF repos (Sigstore, AllStar etc.) here.
3) Do a release once we have confidence things are going smoothly.

There are some final touches still pending, but it shouldn't affect functionality and will mostly not be changes to scorecard-action code (i.e these are changes in Scorecard API and e2e tests). 

Thoughts/feedback?

**Comment by naveensrinivasan** [comment]
> @laurentsimon @naveensrinivasan @justaugustus - work on Golang action is now feature complete. So I'm proposing that we:
> 
> 1. Lockdown any changes/features to Bash code.
> 2. Make a pre-release of the Golang Action code and ask some maintainers to become early adopters and provide feedback. Can take help from OSSF repos (Sigstore, AllStar etc.) here.
> 3. Do a release once we have confidence things are going smoothly.
> 
> There are some final touches still pending, but it shouldn't affect functionality and will mostly not be changes to scorecard-action code (i.e these are changes in Scorecard API and e2e tests).
> 
> Thoughts/feedback?

👍  Sounds like a plan! Thanks for doing this!

**Comment by laurentsimon** [comment]
SGTM too!

**Comment by azeemshaikh38** [comment]
This is now feature complete. Can track the rollout separately.
