### ISSUE TITLE
Scorecard action fails with a fork

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard-action#135]
https://github.com/ossf-tests/scorecard-action
```
/usr/bin/docker run --name a95ec22592ac644c40c2acf9b34b0e2c2c7b_f20[8](https://github.com/ossf-tests/scorecard-action/runs/5486923378?check_suite_focus=true#step:4:8)04 --label 2[9](https://github.com/ossf-tests/scorecard-action/runs/5486923378?check_suite_focus=true#step:4:9)a95e --workdir /github/workspace --rm -e INPUT_RESULTS_FILE -e INPUT_RESULTS_FORMAT -e INPUT_REPO_TOKEN -e INPUT_PUBLISH_RESULTS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/scorecard-action/scorecard-action":"/github/workspace" 29a95e:c22592ac644c40c2acf9b34b0e2c2c7b
Event file: /github/workflow/event.json
Event name: push
Ref: refs/heads/main
Repository: ossf-tests/scorecard-action
Fork repository: null
Private repository: null
Publication enabled: true
Format: sarif
Policy file: /policy.yml
Default branch: refs/heads/null
The 'repo_token' variable is empty.
Please follow the instructions at https://github.com/ossf/scorecard-action#authentication to create the read-only PAT token.
```

https://github.com/ossf-tests/scorecard-action/runs/5486923378?check_suite_focus=true

**Comment by laurentsimon** [comment]
There are other problems to running actions on fork: certain checks may not work properly, e.g. Fuzzing, etc
I think supporting fork needs more thinking, unless we only want scorecard action to not fail.

**Comment by naveensrinivasan** [comment]
OK, Do we need this part of e2e tests?


If it isn't supported do we have to call it out?

**Comment by laurentsimon** [comment]
I think we should add it in the doc, agreed. I've added it in he list in https://github.com/ossf/scorecard-action/issues/80

**Comment by laurentsimon** [comment]
you mean once GitHub team gives us green light to use the `secrets.GITHUB_TOKEN`, or now?

**Comment by azeemshaikh38** [comment]
I mean right now in the test. I don't think using a PAT for every e2e test is scalable. We cannot avoid it for special tests like private repos or branch protection e2e, but otherwise we should use `{ GITHUB_TOKEN }` by default for all e2e tests we write.

**Comment by naveensrinivasan** [comment]
> I mean right now in the test. I don't think using a PAT for every e2e test is scalable. We cannot avoid it for special tests like private repos or branch protection e2e, but otherwise we should use `{ GITHUB_TOKEN }` by default for all e2e tests we write.

I agree.

**Comment by laurentsimon** [comment]
So we'll have to disable the Branch Protection check for the run, correct?

**Comment by azeemshaikh38** [comment]
Oh wait, I'm not suggesting we move to `GITHUB_TOKEN` in production, this is only for the e2e tests. And since `Branch-Protection` will silently get ignored, we don't have to disable them explicitly in the e2e tests.

**Comment by laurentsimon** [comment]
gotcha. By silent ignore, you mean only the branch protection check will fail and the action will ignore the `-1` inconclusive results. SGTM

**Comment by azeemshaikh38** [comment]
> By silent ignore, you mean only the branch protection check will fail and the action will ignore the `-1` inconclusive results.

Yep, that's correct.

**Comment by azeemshaikh38** [comment]
This is now fixed, we have e2e tests for forks.
