### ISSUE TITLE
HTTP 500 error when running the action on ubuntu-24.04 runner

### ISSUE THREAD

**Issue by afuetterer** [ossf/scorecard-action#1381]
Hi,

I just recently updated a few of my CI workflows to use `ubuntu-24.04`. I then realized that the ` scorecard-action` (v2.3.3) failed with HTTP 500.

```
2024/05/17 15:32:14 error sending scorecard results to webapp: http response 500, status: 500 Internal Server Error, error: {"code":500,"message":"something went wrong and we are looking into it."}

2024/05/17 15:32:14 retrying in 1s...
2024/05/17 15:32:16 error sending scorecard results to webapp: http response 500, status: 500 Internal Server Error, error: {"code":500,"message":"something went wrong and we are looking into it."}

2024/05/17 15:32:16 retrying in 3s...
2024/05/17 15:32:19 error sending scorecard results to webapp: http response 500, status: 500 Internal Server Error, error: {"code":500,"message":"something went wrong and we are looking into it."}

2024/05/17 15:32:19 retrying in 10s...
2024/05/17 15:32:29 error processing signature: error sending scorecard results to webapp: http response 500, status: 500 Internal Server Error, error: {"code":500,"message":"something went wrong and we are looking into it."}
```

See https://github.com/afuetterer/oaipmh-scythe/actions/runs/9129167750/job/25108096361

Is the runner not supported or am I doing something wrong here?

**Comment by spencerschrock** [comment]
It's not supported, but only because it's new/beta and we didn't add it yet.
https://github.com/ossf/scorecard-webapp/blob/7af00ace6390e4e3eef8a88a1d6d35f7bfff33ab/app/server/verify_workflow.go#L52-L60

Should be fixed after https://github.com/ossf/scorecard-webapp/pull/637 is merged and deployed to our API. No change will be needed on your end

**Comment by afuetterer** [comment]
Thanks for the response, looking forward to it.

**Comment by spencerschrock** [comment]
This is now deployed

**Comment by spencerschrock** [comment]
> Hi 👋
> 
> I'm getting this problem, and am not sure what to do. Is this fixed or a recurrent?
> 
> Error message after sigstore verification:
> 
> > error sending scorecard results to webapp: http response 500, status: 500 Internal Server Error, error: {"code":500,"message":"something went wrong and we are looking into it."}

@bytemare do you have a link to the public repo that's having this error? I can take a look

**Comment by bytemare** [comment]
Bullseye! Thank you @spencerschrock !

It must have fallen out somehow when I moved some things around. Sorry for the disturbance 🙏 

Thank you for all the amazing work on this project, I really enjoy it and use it on all my open source repos 😃
