### ISSUE TITLE
Installation instructions should be updated/improved

### ISSUE THREAD

**Issue by Wavyeli32** [ossf/scorecard-action#1409]
After following the[ installation instructions](https://github.com/ossf/scorecard-action#installation), our group found that the following can be updated/improved:

- Outdated screenshots
- Add additional step in instructions (search workflow for OSSF)

Me and @silasvm, @jordin221, @JeremiahAHoward, @klbynum, @emmet0r would love to work on this problem!

**Comment by spencerschrock** [comment]
Can you take a look at #1403 to see what was started? It seems like there are multiple paths that may be needed

**Comment by Wavyeli32** [comment]
Thank you so much for the quick response and link to the PR! We had a look, and this is exactly what we're trying to implement.

We agree with your comments and also think multiple paths should be represented.

We noticed #1403 was closed by the creator without being merged, even though they had done most of the required work. We are still happy to work on this, but how would you like us to proceed?

**Comment by spencerschrock** [comment]
@marcinguy do you have a desire/time to continue your patch? Or would you prefer to hand it off?

**Comment by klbynum** [comment]
Hi @spencerschrock, would you like to wait more time for a reply from @marcinguy? If not, we are happy to pick up where they left off, incorporate their work, and credit them in the resulting PR (I am in the group that opened this issue).

**Comment by spencerschrock** [comment]
All yours!
