### ISSUE TITLE
go code out of sync with entrypoint.sh

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard-action#156]
See https://github.com/ossf/scorecard-action/pull/155#issuecomment-1075758252:
1. this PR https://github.com/ossf/scorecard-action/pull/98
2. this https://github.com/ossf/scorecard-action/pull/155

**Comment by laurentsimon** [comment]
cc @justaugustus

**Comment by laurentsimon** [comment]
@azeemsgoogle do you know if these have already been resolved?

**Comment by azeemshaikh38** [comment]
Changes already merged into Bash (#98) should be resolved by #489. The other issues mentioned are still WIP so I'm not sure if those changes have been resolved/are in sync with Golang.

**Comment by laurentsimon** [comment]
IFAICT, `setRepoInfo` is out of sync with the bash script. I uses `curl https://api.github.com/repos/"$GITHUB_REPOSITORY"` in the bash

but uses `cat $GITHUB_EVENT_PATH` in the golang.

This was a source of problems on private repos, e.g. https://github.com/ossf/scorecard-action/pull/75

Also, I see that `setPublishResults()` uses `o.PublishResults = o.PublishResults && !privateRepo`. If an err is reported in `strconv.ParseBool(o.PrivateRepoStr)`, `privateRepo` will default to false and publish would be set to true. I think we should err on the safe side: when we cannot parse, we should fail.

**Comment by azeemshaikh38** [comment]
You are right, I see the failure here - https://github.com/ossf-tests/scorecard-action/runs/6996850405?check_suite_focus=true. It says `refs/heads/main` not supported, I'm assuming this is due to `GITHUB_EVENT_PATH` not being set.

re: `setPublishResults()`, ack. Will send out a PR to fix this.

**Comment by azeemshaikh38** [comment]
Closing this issue. Golang code is now in sync with Bash.
