### ISSUE TITLE
Setup e2e

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard-action#159]
@naveensrinivasan could you help with setting up e2e test for this? Basically, just like we have e2e tests today pointing to `@main`, can have a separate workflow in the test repos pointing to `@golang-staging` branch. That way, it'll be easy to figure out any breakages or differences between the 2 versions.

_Originally posted by @azeemshaikh38 in https://github.com/ossf/scorecard-action/issues/158#issuecomment-1083656204_

**Comment by laurentsimon** [comment]
Another e2e tests I'd like to have: not sure if it should live here or under the scorecard repo: to enable `GITHUB_TOKEN` instead of PAT, we need to validate it all still works, except for the Branch-Protection setting. I think this can live under the main scorecard repo. Wdut?

**Comment by naveensrinivasan** [comment]
This has been fixed.
