### ISSUE TITLE
Discussion: remove `output_format` from action input

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard-action#17]
The action takes an `output_format` as input, which may be sarif or json.
The action also takes an `output_file`. I'm wondering if we should simplify and remove the `output_format`?
We could use the extension of the `output_file` (results.sarif or results.json) to infer the format the use wants.

I think keeping the `output_format` is OK, but wanted to touch base and have everyone's opinion.

wdut?

cc @oliverchang @azeemshaikh38 @naveensrinivasan

**Comment by azeemshaikh38** [comment]
Remind me again what `output_format: json` is needed for? Also, do we need `output_format` and `output_file` at all? Can this not be hidden under the hood?

**Comment by laurentsimon** [comment]
re: output format -> users may want to get the output as SARIF or JSON depending on their needs/use cases.
re: output_file: -> users can use the result any way they want. We just happen to ask them to submit the SARIF output to GitHub in their workflow, but they are free to do other things and explore other use cases.

**Comment by azeemshaikh38** [comment]
I see. In that case, I vote to *not* rely on the output file's name to infer the format.

**Comment by oliverchang** [comment]
> I see. In that case, I vote to _not_ rely on the output file's name to infer the format.

+1 to being more explicit.

**Comment by laurentsimon** [comment]
Thanks all for the confirmation. Closing!
