### ISSUE TITLE
End-to-end tests for workflow_dispatch

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard-action#179]
We need to trigger a "manual" workflow_dispatch event using this API https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event

/cc @naveensrinivasan

**Comment by naveensrinivasan** [comment]
1. Workflow dispatch for golang branch https://github.com/ossf-tests/scorecard-action/blob/90f8df25accc87559287ef3d4ad8e6f151c9f1df/.github/workflows/workflowdispatch-golang.yml#L1
2. Workflow dispatch for main branch https://github.com/ossf-tests/scorecard-action/blob/90f8df25accc87559287ef3d4ad8e6f151c9f1df/.github/workflows/workflowdispatch.yml#L1

**Comment by laurentsimon** [comment]
> 1. Workflow dispatch for golang branch https://github.com/ossf-tests/scorecard-action/blob/90f8df25accc87559287ef3d4ad8e6f151c9f1df/.github/workflows/workflowdispatch-golang.yml#L1

do we need to update this to a different branch? https://github.com/ossf-tests/scorecard-action/blob/90f8df25accc87559287ef3d4ad8e6f151c9f1df/.github/workflows/workflowdispatch-golang.yml#L36

**Comment by laurentsimon** [comment]
@naveensrinivasan let me know if you have some update on this one. I've updated the doc in https://github.com/ossf/scorecard-action/pull/203, saying that workflow_dispatch is experimental for now.

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan let me know if you have some update on this one. I've updated the doc in #203, saying that workflow_dispatch is experimental for now.

Can we sync up to go over this?

**Comment by azeemshaikh38** [comment]
workflow_dispatch e2e tests now setup and working. Closing this.
