### ISSUE TITLE
End-to-end tests for GITHUB_TOKEN

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard-action#180]
Add e2e tests using the default GITHUB_TOKEN

/cc @naveensrinivasan

**Comment by naveensrinivasan** [comment]
Here are actions with GitHub Token



Public repo - https://github.com/ossf-tests/scorecard-action/blob/6acbb7d090d1cfff7c51c58b8fc501c87e327995/.github/workflows/scorecards.yml#L35

Private repo - https://github.com/test-organization-ls/scorecard-action-private-repo-tests/blob/577c5bb3ceb1c636b277ae159a0ef115c1c0c9fd/.github/workflows/scorecard.yml#L35

**Comment by laurentsimon** [comment]
Thanks. I'm going to make a change to the action so that the GITHUB_TOKEN is the default value if not token is provided by the user. I'll cc you on the PR. Once it's merged, can we add 2 more tests with no token provided, to verify it all works as well?

**Comment by naveensrinivasan** [comment]
> Thanks. I'm going to make a change to the action so that the GITHUB_TOKEN is the default value if not token is provided by the user. I'll cc you on the PR. Once it's merged, can we add 2 more tests with no token provided, to verify it all works as well?

Will do that!

**Comment by naveensrinivasan** [comment]
### Main branch without any token
https://github.com/ossf-tests/scorecard-action/actions/runs/2192902943
https://github.com/ossf-tests/scorecard-action/blob/d955b923ca38d81e755a8d77533f121cf5a8dbb3/.github/workflows/scorecards-without-token.yml#L36

### Private repo without any token
https://github.com/test-organization-ls/scorecard-action-private-repo-tests/actions/runs/2192919167
https://github.com/test-organization-ls/scorecard-action-private-repo-tests/blob/76cee4494a9e2b62b22417386a4a219b47e56bec/.github/workflows/scorecards-without-token.yml#L35

**Comment by laurentsimon** [comment]
All working, great!
Are all these new tests documented in https://github.com/ossf/scorecard-action/tree/main/e2e?

I think they are, just double-checking. I wonder if README in the 2 ossf-tests repos should also list what each workflow does. Nothing fancy, just something to speed up maintainers when adding tests.

Thanks again for all this @naveensrinivasan getting closer to our ext release!

**Comment by laurentsimon** [comment]
Is https://github.com/ossf/scorecard-action/tree/main/e2e failing? One of the tests is red

**Comment by laurentsimon** [comment]
I see. If it fails, should the icon be green in the sense that the e2e test "passes"? I find it confusing that it says fail: it'd like the scorecard run to fail, but the results of the e2e2 test to says "succeed", ie expected behavior. Is this do-able?

**Comment by naveensrinivasan** [comment]
> I see. If it fails, can we make the icon green in the sense that the e2e test "passes"? I find it confusing that it says fail: it'd like the scorecard run to fail, but the results of the e2e2 test to says "succeed", ie expected behavior. Is this do-able?

I don't know how to do that. But the job will create an issue only if it succeeds https://github.com/ossf-tests/scorecard-action-non-main-branch/blob/b8070100a8883f2a0ebba1b066e5c55fe5469857/.github/workflows/scorecard-analysis.yml#L57

**Comment by laurentsimon** [comment]
Got it. Can you add a note in the README to say that it's expected to fail? Otherwise when looking at the results, it seems like something is failing.

If everything works, shall we close the open issues regarding failed runs:
https://github.com/ossf/scorecard-action/issues/183
https://github.com/ossf/scorecard-action/issues/182
https://github.com/ossf/scorecard-action/issues/189
?

**Comment by naveensrinivasan** [comment]
> Got it. Can you add a note in the README to say that it's expected to fail? Otherwise when looking at the results, it seems like something is failing.
> 
> If everything works, shall we close the open issues regarding failed runs:
> 
> * [ ]  [Failed to run automated scorecard-action@main test-organization-ls/scorecard-action-private-repo-tests #183](https://github.com/ossf/scorecard-action/issues/183)
> * [ ]  [Failed to run automated scorecard-action@golang-staging test-organization-ls/scorecard-action-private-repo-tests #182](https://github.com/ossf/scorecard-action/issues/182)
> * [ ]  [Failed to run automated scorecard-action@main test-organization-ls/scorecard-action-private-repo-tests #189](https://github.com/ossf/scorecard-action/issues/189)
>   ?

I can update the README tomorrow. 

Yes, you can close them. Thanks!

**Comment by laurentsimon** [comment]
Closed, thanks!
