### ISSUE TITLE
Failed to run automated scorecard-action@golang-staging test-organization-ls/scorecard-action-private-repo-tests

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard-action#182]
https://github.com/test-organization-ls/scorecard-action-private-repo-tests/actions/runs/2175340751

**Comment by naveensrinivasan** [comment]
`e2e` is failing for the `golang-staging` branch

**Comment by laurentsimon** [comment]
that has to do with cosign API and work @rohankh532 did. @rohankh532 did we set up the `COSIGN_EXPERIMENTAL=1` in the code?

@naveensrinivasan can you confirm this result is for the go (not bash entrypoint.sh)?

**Comment by rohankh532** [comment]
> that has to do with cosign API. @rohankh532 did we set up the `COSIGN_EXPERIMENTAL=1` in the code?
> 
> @naveensrinivasan can you confirm this result is for the go (not bash entrypoint.sh)?

I think this issue is because id-token isn't set to write in the [workflow](https://github.com/test-organization-ls/scorecard-action-private-repo-tests/actions/runs/2175340751/workflow)

**Comment by laurentsimon** [comment]
Thanks @rohankh532 !

**Comment by laurentsimon** [comment]
closing, as per https://github.com/ossf/scorecard-action/issues/180#issuecomment-1105508516
