### ISSUE TITLE
Incompatible with Apache's GitHub integration

### ISSUE THREAD

**Issue by vy** [ossf/scorecard-action#188]
I've tried to enable OpenSSF Scorecards GitHub Action for the Log4j project, though the INFRA could not proceed with the changes due to the excessive rights required. The issue is tracked in [INFRA-23160](https://issues.apache.org/jira/browse/). Would it be possible to relax the required rights, yet still have a (mostly?) working scorecards?

Please note that this limitation blocks the scorecards action integration for all ASF projects, Log4j has just happened to be the first pilot.

**Comment by vy** [comment]
@azeemshaikh38, thanks so much for the prompt response. I've brought this to INFRA-23160. In the meantime, I will really appreciate it if you can clarify this nuance in the documentation.

**Comment by laurentsimon** [comment]
We'll do that for next release we intend to cut the next couple weeks.

**Comment by azeemshaikh38** [comment]
Documentation is updated. Closing

**Comment by garydgregory** [comment]
> [INFRA-23160](https://issues.apache.org/jira/browse/)

Link is https://issues.apache.org/jira/browse/INFRA-23160
