### ISSUE TITLE
Add branch_protection_rule to workflow trigger

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard-action#19]
I've just found out that there's a trigger to run workflows when branch protection settings change https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#branch_protection_rule

As part of the broader effort to use scorecard results for attestation (e.g., SLSA provenance) I think we should enable this trigger for our workflow. In the beginning we'll just ignore the trigger in our implementation. But later, we can create an attestation for this event (including the payload). Besides its use for attestation, it can also be used to complement the data we collect via push events into our BQ table.

cc @azeemshaikh38 @asraa wdut?

**Comment by azeemshaikh38** [comment]
This is a great find, thanks @laurentsimon! +1 to supporting this trigger. I don't understand why you say:

> In the beginning we'll just ignore the trigger in our implementation

We can support this from the start right? Basically we should be able to support: `cron`, `push` and `branch_protection_rule` triggers in our very first release no?

**Comment by laurentsimon** [comment]
I meant ignoring the trigger for attestation. And definitely I agree we can enable it to update the SARIF results. It should be enough to only run the `--checks Branch-Protection` on this trigger.
