### ISSUE TITLE
PAT optional: README vs entrypoint.sh

### ISSUE THREAD

**Issue by apeabody** [ossf/scorecard-action#248]
Hi Everyone,

The [Readme](https://github.com/ossf/scorecard-action/blob/f859da81d7e01837d5b975533674c721bf36c6dc/entrypoint.sh#L94) states that the PAT is optional except for the [Branch-Protection](https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection)) check.  However with v1.0.4 the [entrypoint.sh exit with an error (1)](https://github.com/ossf/scorecard-action/blob/f859da81d7e01837d5b975533674c721bf36c6dc/entrypoint.sh#L94) if a PAT isn't present.  It would be preferable to have the option of not using a PAT for all repos.  Thanks!

**Comment by laurentsimon** [comment]
Hi

sorry about that. We have updated the readme but we have not cut the release yet. We're going to cut a release in the next few days, and the PAT won't be necessary in the new release.

Please stay tuned :-)

**Comment by apeabody** [comment]
Terrific - Thank you!
