### ISSUE TITLE
BUG: gostaging

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard-action#277]
gostaging is broken due to https://github.com/ossf/scorecard/pull/1898.

One way to fix it is for the go code to grab env variables and call scorecard CLI/API with the correct options set. This decouples scorecard CLI and the Action code.

**Comment by justaugustus** [comment]
(Discussed [here](https://openssf.slack.com/archives/C0235AR8N2C/p1653431862505869?thread_ts=1653419973.820599&cid=C0235AR8N2C): I'll take care of fixing this break)

**Comment by justaugustus** [comment]
Should be fixed with the merge of https://github.com/ossf/scorecard-action/pull/313, but feel free to reopen, if needed!
