### ISSUE TITLE
Disable Signed-Releases

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard-action#28]
The Signed-Releases check encourage developers to sign their artifacts locally using keys they manage locally (see https://github.com/ossf/scorecard/blob/main/docs/checks.md#signed-releases).  I think we may want to remove this check from the action until cosign officially announces OIDC flow + verification. We're going to be asking users to switch to keyless cosign anyway later - in accordance with SLSA. 

At this point we'll be able to tell users to use cosign keyless, and maybe give *some* points to those that use some sort of signature.

cc @asraa @azeemshaikh38 @naveensrinivasan 

wdut?

**Comment by azeemshaikh38** [comment]
My vote would be to keep it for now. We will update the scope of this check to verify Cosign/Rekor usage in future anyways, so can update the check then instead of removing it and re-adding it.

**Comment by laurentsimon** [comment]
The issue is that the recommendations are not good: using PGP in an ad-hoc way is not a good recommendation. If we were to remove it, it's easy to re-enable it on next update. To me this is better than saying "Please use PGP" and 1 month later say "Please use cosign". I imagine we would give higher score for keyless cosign than for PGP.

**Comment by azeemshaikh38** [comment]
Makes sense. I was trying to avoid removing the check from Scorecard repo itself since this can affect the weekly data. If this is for Scorecard Actions, we can simply use `--checks` flag to remove `Signed-Releases` check. Wdut?

**Comment by laurentsimon** [comment]
sorry for the confusion. This is what I meant: remove from action only. I'll send a PR to do that now.
