### ISSUE TITLE
Segmentation violation

### ISSUE THREAD

**Issue by dthaler** [ossf/scorecard-action#323]
https://github.com/microsoft/ebpf-for-windows/runs/6676366019?check_suite_focus=true hit the following running with [ossf/scorecard-action@5c8bc69dc88b65c66584e07611df79d3579b0377](https://github.com/ossf/scorecard-action/commit/5c8bc69dc88b65c66584e07611df79d3579b0377)

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd9dca6]

**Comment by azeemshaikh38** [comment]
@laurentsimon the crash is happening in the `remediationSetup` func. Could you take a look?

**Comment by laurentsimon** [comment]
I'll cut a new release for Scorecard and then the Action. The bug is fixed in https://github.com/ossf/scorecard/pull/1947, but was not included in the latest release.
Sorry about that.

Thanks @azeemshaikh38 for the pointer!

**Comment by laurentsimon** [comment]
Release for Scorecard https://github.com/ossf/scorecard/releases/tag/v4.3.1
I have sent the PR for the Action https://github.com/ossf/scorecard-action/pull/324

**Comment by laurentsimon** [comment]
Closing. Re-open if this is still a problem. Thanks!
