### ISSUE TITLE
🐛 Support for ghcr.io in Action

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard-action#35]
I tried using the image generated by our release workflow.
When using ghcr.io in the [action](https://github.com/ossf/scorecard-action/blob/main/action.yaml#L44):
```
runs:
  using: "docker"
  image: "ghcr.io://ossf/scorecard-action:latest"
```

I got the following error
```
'ghcr.io://ossf/scorecard-action:latest' should be either '[path]/Dockerfile' or 'docker://image[:tag]'
```

When trying 
```
runs:
  using: "ghcr.io"
  image: "ghcr.io://ossf/scorecard-action:latest"
```

I got 
```
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: ghcr.io' is not supported, use 'docker', 'node12' or 'node16' instead.')
```

@naveensrinivasan am I doing something wrong or is docker registry the only registry supported?
cc @azeemshaikh38

**Comment by azeemshaikh38** [comment]
See image below. 2 things:

1. Looks like we can use a non Docker hub image if needed.
2. We can directly reference `Dockerfile` and let GitHub actions build and run that image.

 I personally prefer option (2) if that can be done. Wdut?


![image](https://user-images.githubusercontent.com/4825078/147898449-537f0dd0-c197-4af3-a751-9e232de6527c.png)

**Comment by laurentsimon** [comment]
I like option 2 too, which is what I opted for for this https://github.com/ossf/scorecard-action/pull/38. If you're OK with the PR, plz LGTM and I'll cut a release to start testing.
