### ISSUE TITLE
Question: custom icon on marketplace

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard-action#40]
Is it possible to have a custom icon for our action on the marketplace?
Currently we use a default "mic" https://github.com/marketplace/actions/ossf-scorecard-action.

The documentation at https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding seems to suggest we can only pick from the list here https://feathericons.com/

Is that true? Will the icon used in the starter-workflows be used on the marketplace too?

cc @josepalafox

**Comment by laurentsimon** [comment]
cc @azeemshaikh38

**Comment by josepalafox** [comment]
I can get you the custom icon, can you provide the svg file for the icon
you want to use?

**Comment by abirismyname** [comment]
I would recommend either [openssf-icon-color.svg](https://raw.githubusercontent.com/ossf/artwork/master/openssf/icon/color/openssf-icon-color.svg) or [openssf-icon-black.svg](https://raw.githubusercontent.com/ossf/artwork/master/openssf/icon/black/openssf-icon-black.svg)

**Comment by laurentsimon** [comment]
@abiri

> I would recommend either [openssf-icon-color.svg](https://raw.githubusercontent.com/ossf/artwork/master/openssf/icon/color/openssf-icon-color.svg) or [openssf-icon-black.svg](https://raw.githubusercontent.com/ossf/artwork/master/openssf/icon/black/openssf-icon-black.svg)

These looks great! @josepalafox please use the color one [openssf-icon-color.svg](https://raw.githubusercontent.com/ossf/artwork/master/openssf/icon/color/openssf-icon-color.svg)

Thank you so much for the help!

**Comment by abirismyname** [comment]
Logo updated. Should be able to close this issue now.

**Comment by laurentsimon** [comment]
Thank you @abirismyname !
