### ISSUE TITLE
Make structure compatible with GitHub marketplace

### ISSUE THREAD

**Issue by oliverchang** [ossf/scorecard-action#5]
Would it be possible to follow the required structure [here](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#about-publishing-actions) to make this more easily discoverable on the marketplace? 

The main requirement is that `action.yml` lives in the root (and that there is only 1 action per repo).

**Comment by laurentsimon** [comment]
ah, was not aware of this requirement. We certainly can. It's a little inconvenient but I don't think there's a way around it. Thanks for pointing this out!
