### ISSUE TITLE
Using the built-in GitHub token as default for the token input

### ISSUE THREAD

**Issue by EndBug** [ossf/scorecard-action#64]
Hi, I just have a quick question/suggestion: I've seen that you set up your inputs so that the user has to create a PAT to use with the action.
Is there a reason why you don't use the built-in token as default, neither recommend doing so?

**Comment by azeemshaikh38** [comment]
This is due to a limitation in the default token to make GitHub API calls. Please see this comment and thread for more details - https://github.com/ossf/scorecard/issues/1097#issuecomment-985756627

**Comment by azeemshaikh38** [comment]
Note that we are still exploring the possibility (and would very much prefer) to use the default token instead of PAT. But if the limitation is too restrictive, users may need to continue using a PAT.

**Comment by EndBug** [comment]
Got it, thanks for the quick reply :)
