### ISSUE TITLE
Error: GitHub token env var is not set.

### ISSUE THREAD

**Issue by nibanks** [ossf/scorecard-action#70]
I just encountered [this error](https://github.com/csujedihy/msquic/runs/4967983336?check_suite_focus=true) in during a run of our scorecard action:
```
...
Format: sarif
Policy file: /policy.yml
Default branch: refs/heads/main
2022/01/27 14:59:48 GitHub token env var is not set. Please read https://github.com/ossf/scorecard#authentication
```
The link there seems to be indicating that I should create another PAT and set `GITHUB_AUTH_TOKEN` to it. I don't understand this. I already pass `repo_token` to this step ([here](https://github.com/microsoft/msquic/blob/main/.github/workflows/scorecards-analysis.yml#L38)), and it has the scope (`public_repo`) recommended in the authentication steps. Why isn't the `repo_token` being used to avoid the rate limit?

If this absolutely is necessary, then why didn't the default setup instructions include this requirement up front?

**Comment by azeemshaikh38** [comment]
@nibanks is this an error you are seeing only on your forked repo or is this also happening on the original repo? 

Also, can you confirm if you added your PAT to your forked repository's secrets?

@laurentsimon fyi.

**Comment by nibanks** [comment]
Ah! You're right. I didn't even notice it was on a fork. Now everything makes sense. I wonder if there's a way to somehow make this more obvious? I guess in this case, `repo_token` was empty, right? Maybe call that out explicitly?

**Comment by laurentsimon** [comment]
thanks for the report. There are also some checks that don't make much sense on forked repo, like Fuzzing and CII-Badges, I think.

You're right, `repo_token` must have been empty. So what you're asking is to say "GH token is declared but is empty. Have you created the `repo_token` for your fork? Please follow these steps to create the PAT". Would that work?

**Comment by nibanks** [comment]
@laurentsimon that would be perfect. Thanks for helping with my issue!
