### ISSUE TITLE
`Only the default branch 'refs/heads/null' is supported` after #68 landed

### ISSUE THREAD

**Issue by ChrisCarini** [ossf/scorecard-action#73]
Hello, I am getting the below error after #68 (fix for #66) landed and was picked up by my workflow:

```
Event file: /github/workflow/event.json
Event name: schedule
Ref: refs/heads/master
Private repository: null
Publication enabled: true
Format: sarif
Policy file: /policy.yml
Default branch: refs/heads/null
refs/heads/master not supported with 'schedule' event.
Only the default branch 'refs/heads/null' is supported
```
(**ref:** [link](https://github.com/ChrisCarini/environment-variable-settings-summary-intellij-plugin/runs/4955265412?check_suite_focus=true))

This is happening on the scheduled runs of the workflow I have configured.

@laurentsimon - when you have a moment to take a look, could you help investigate? The repo in which this is run has the default branch set to `master`.

Thank you!

**Comment by laurentsimon** [comment]
Thanks. I think I know what's happening. The `schedule` trigger does not seem to have an associated branch, which is unexpected from me. I'll work on a fix.

cc @naveensrinivasan let's add better unit test for the action.

**Comment by laurentsimon** [comment]
fyi, I've created a support ticket with GitHub.

**Comment by ChrisCarini** [comment]
Awesome, thank you @laurentsimon !

**Comment by ChrisCarini** [comment]
SGTM, and no worries! Appreciate you looking into this (and #84 😄 )!
