### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard-action#80]
- [ ] Explain that the results will only be available once a new commit is pushed. We can have a `workflow_dispatch` trigger users can trigger manually the first time to see the results flow
- [ ] Explain where to find the reason why a run failed
- [ ] Move users to GITHUB_TOKEN
- [ ] support for workflow_dispatch
- [ ] Explain whether pull request trigger is supported or not
- [ ] Call out that running scorecard on forks is not officially supported
- [ ] Orgs may need to enable GitHub Advanced Security https://github.com/ossf/scorecard-action/issues/134#issuecomment-1064197494
- [ ] Explain the difference of PAT permissions that are needed
- [ ] In the starter workflow and our example workflow, remove the PAT. Have a commented out line for PAT, with a link to generate the PAT using the URL + the URL to create the repo secret

**Comment by laurentsimon** [comment]
cc @naveensrinivasan added `Call out that running scorecard on forks is not officially supported`, per our discussion in https://github.com/ossf/scorecard-action/issues/135

**Comment by naveensrinivasan** [comment]
> cc @naveensrinivasan added `Call out that running scorecard on forks is not officially supported`, per our discussion in #135

Thank you!

**Comment by laurentsimon** [comment]
@naveensrinivasan thanks for all the e2e tests, it's great. Is there a way to document where to look for, for example for workflow_dispatch, schedule, push and pull_request triggers. Where to find them :-)?

Thanks!
