### ISSUE TITLE
BUG: Getting a score -1 due to Branch-Protection check

### ISSUE THREAD

**Issue by miguelnietoa** [ossf/scorecard-action#895]
**Describe the bug**
The score is not shown in the badge due to an internal error. Notice the JSON blow with the `"reason": "internal error: error during branchesHandler.setup: internal error: githubv4.Query: Resource not accessible by integration"`.

API Response:
```json
{
  "date":"2022-09-07",
  "repo":{
    "name":"github.com/kommitters/editorjs-toggle-block",
    "commit":"58c327968b01569437633c3b1958cd858e63ea38"
  },
  "scorecard":{
    "version":"v4.3.1",
    "commit":"70d045b9ef00e7171ce3950aca38eef6ea4d7308"
  },
  "score":-1,
  "checks":[
    {
      "name":"Branch-Protection",
      "score":-1,
      "reason":"internal error: error during branchesHandler.setup: internal error: githubv4.Query: Resource not accessible by integration",
      "details":null,
      "documentation":{
        "short":"Determines if the default and release branches are protected with GitHub's branch protection settings.",
        "url":"https://github.com/ossf/scorecard/blob/70d045b9ef00e7171ce3950aca38eef6ea4d7308/docs/checks.md#branch-protection"
      }
    }
  ]
}
```

**Expected behavior**
API Response should include the score different from `-1`.

**Comment by azeemshaikh38** [comment]
I think this is because you updated your BranchProtection settings which triggered a new scorecard-action run. But the problem was [this line](https://github.com/ossf/scorecard-action/blob/main/options/options.go#L187) which only runs Branch-Protection check. #896 should fix this. But also, if you re-run the scorecard-action workflow it should fix it too.

**Comment by azeemshaikh38** [comment]
Fixed in https://github.com/ossf/scorecard-action/releases/tag/v2.0.2

**Comment by miguelnietoa** [comment]
> Fixed in https://github.com/ossf/scorecard-action/releases/tag/v2.0.2

Thanks @azeemshaikh38 🎉
