### ISSUE TITLE
Code Coverage tracking

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard-action#92]
Install codecov for coverage tracking.

**Comment by naveensrinivasan** [comment]
https://app.codecov.io/gh/ossf

@david-a-wheeler  Could you help with the installation similar to scorecard repo?

**Comment by naveensrinivasan** [comment]
@david-a-wheeler a friendly reminder.

**Comment by jmertic** [comment]
@naveensrinivasan I've approved this install now for the full GH org; let me know if you'd prefer to restrict it specific repos instead.

**Comment by jmertic** [comment]
Excellent! We should be good to go.
