### ISSUE TITLE
Next minor release v1.1.0

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard-action#97]
- [x] https://github.com/ossf/scorecard-action/issues/180
- [ ] ~~https://github.com/ossf/scorecard-action/issues/179~~
- [x] https://github.com/ossf/scorecard-action/issues/84
- [x] https://github.com/ossf/scorecard-action/issues/80
- [ ] ~~https://github.com/ossf/scorecard-action/issues/154~~
- [x] https://github.com/ossf/scorecard-action/issues/78
- [x] https://github.com/ossf/scorecard-action/issues/110
- [x] https://github.com/ossf/scorecard-action/issues/196
- [x] https://github.com/ossf/scorecard-action/issues/198
- [ ] https://github.com/ossf-tests/scorecard-action-results/pull/2
- [X] ~~https://github.com/ossf/scorecard/issues/1320~~ non blocking so skipping
- [x] ~~https://github.com/ossf/scorecard/issues/1850#issuecomment-1112580628~~ First iteration of the issue completed

**Comment by azeemshaikh38** [comment]
+1.

**Comment by laurentsimon** [comment]
[optional] support for pull requests https://github.com/ossf/scorecard-action/issues/109

**Comment by laurentsimon** [comment]
should resolve https://github.com/ossf/scorecard-action/issues/110 too

**Comment by laurentsimon** [comment]
would love to have this resolved https://github.com/ossf/scorecard-action/issues/143

**Comment by laurentsimon** [comment]
Let's try to add a timeline for this release, to avoid delaying further. I think we have enough content. I propose by 15 April. Any objection? We can finalize this on our next sync.

**Comment by laurentsimon** [comment]
Let me try to do that for mi April

**Comment by laurentsimon** [comment]
Having debug messages in the output for troubleshooting would be useful. It's been an ask from time to time. I don't think we can do that for this release, but for the next one when we switch to golang library we should be able to do it.

**Comment by naveensrinivasan** [comment]
> /cc @naveensrinivasan let us know when some of the e2e tests are done. I'll start working on the documentation myself

@laurentsimon Tests are done, and everything looks good. https://github.com/ossf/scorecard-action/issues/180#issuecomment-1103294776

**Comment by laurentsimon** [comment]
Great, Feel free to close the 2 issues related to e2e test listed in the first description

**Comment by laurentsimon** [comment]
Looks like we have all TODOs done for this release

**Comment by azeemshaikh38** [comment]
Closing this since looks like this is done. Please re-open if needed.
