### ISSUE TITLE
BUG TUF invalid key when running Scorecard Github Action 

### ISSUE THREAD

**Issue by joycebrum** [ossf/scorecard-action#998]
## Description
Version: 2.0.3

The action crashes with the error `2022/10/28 13:59:29 error signing scorecard json results: error signing payload: getting key from Fulcio: verifying SCT: updating local metadata and targets: error updating to TUF remote mirror: tuf: invalid key`

I've tested in one repo to upgrade the scorecard-action to 2.0.6 and the error didn't happened anymore. Don't know if the error is just random or if it was really solved on the latest release.

It seems to be related to the error https://github.com/sigstore/cosign/issues/2390.

## Examples
https://github.com/dmlc/xgboost/pull/8263#issuecomment-1294613038
https://github.com/cert-manager/cert-manager/actions/runs/3345975741

**Comment by faximan** [comment]
+1
This went away when I changed to `publish_results: false` even though the comment says the value is ignored for private repos (seems like it isn't).

**Comment by joycebrum** [comment]
Described and fixed in https://github.com/ossf/scorecard-action/issues/997 (release 2.0.6)

**Comment by joycebrum** [comment]
Described and fixed in https://github.com/ossf/scorecard-action/issues/997 (release 2.0.6)
